name: SMPStatistics
version: '${project.version}'
main: com.learnspigot.smp.statistics.SMPStatistics
api-version: 1.18
authors: ["Bungoh", "Reece", "Devous"]
description: Statistics tracker for LearnSpigot SMP
depend:
  - "PlaceholderAPI"
